Generate a new dummy node for each test
stackhpc/stackhpc-ipa-hardware-managers pull request #4
Opened 2018-03-09 17:40 UTC by jovial

Previously the dummy node was being reused without using a deep copy. Some
tests were modifying the dictionary. This caused tests to fail if they were run
in same worker process.

The behaviour could be triggered when running the test suite with the serial flag
or when the number of tests was greater than the number of installed processors
(default behaviour is one worker process per cpu).

A new data structure is now created for each test. This fixes issue #3.

2018-03-09 17:43 UTC, dougszumski approved these changes
Good spot!

2018-03-09 17:45 UTC, dougszumski requested changes
Need to fix pep8.

2018-03-09 17:48 UTC, dougszumski approved these changes

2018-03-12 09:17 UTC, markgoddard approved these changes

2018-03-13 09:28 UTC, merged