Add a proposal for a network interface firmware checker
stackhpc/stackhpc-ipa-hardware-managers pull request #6
Opened 2018-03-22 17:11 UTC by jovial

This is an initial attempt to write a spec for the NIC firmware checker. Feedback would be appreciated.

2018-03-22 17:50 UTC, oneswig requested changes
Good start Will, detach the dependency on our hardware-manager repo if you can.

2018-03-22 17:50 UTC, oneswig commented on specs/system_nic.rst
> +This document proposes an extension to the stackhpc-ipa-hardware-managers
I expect they'd want something that doesn't have an external dependency on our stuff.
That might mean we need to contribute upstream the components we are extending, if necessary.

2018-03-22 17:50 UTC, oneswig commented on specs/system_nic.rst
> +that version.
It may also be worth referencing the security angle (although I expect it'd be possible to create a nobbled firmware with the same version).

2018-03-22 17:50 UTC, oneswig commented on specs/system_nic.rst
> +If a network card is present, and a matching rule exists with the same pci-id,
Might be worth clarifying in this section that you're supplying PCI vendor_id, device_id pairs as a match key.  pci-id might be misunderstood as a bus address.

2018-03-22 17:50 UTC, oneswig commented on specs/system_nic.rst
> +        "firmware_version": "<firmware_version>"
It would be worth stating that you're doing an exact string match on the firmware version.  We aren't planning to decode version syntax and we aren't planning to implement anything like "this version or later".

2018-03-22 18:01 UTC, jovial commented
Just to clarify this was created based on feedback from the code review in https://github.com/stackhpc/stackhpc-ipa-hardware-managers/pull/5#pullrequestreview-106112779, so we could discuss the design without getting bogged down in the implementation details.

2018-03-23 08:59 UTC, oneswig commented
Thanks Will.  Out of interest why is it called "system_nic"?

2018-03-23 13:09 UTC, markgoddard reviewed
Thanks, nice spec.

2018-03-23 13:09 UTC, markgoddard commented on specs/system_nic.rst
> +disk image builder element to facilitate automated checking of network
We want to propose the IPA hardware manager, not the DIB element.

2018-03-23 13:09 UTC, markgoddard commented on specs/system_nic.rst
> +`stackhpc-ipa-hardware-managers` disk image builder (DIB) element. The
hardware manager

2018-03-23 13:09 UTC, markgoddard commented on specs/system_nic.rst
> +order to negate operational differences, all of the devices should run the same
It's a per-node setting, so we can have different versions across a cluster. Or do you mean within a node if it has multiple identical NICs?

2018-03-23 13:09 UTC, markgoddard commented on specs/system_nic.rst
> +
For completeness, existing card with matching firmware

2018-03-23 13:09 UTC, markgoddard commented on specs/system_nic.rst
> +cleaing should always pass.
nit: cleaning

2018-03-23 13:09 UTC, markgoddard commented on specs/system_nic.rst
> +flag can be set in the ironic node info. This will stop checking entirely and
where in the node info?

2018-03-27 08:11 UTC, jovial commented
no good reason why it's called `system_nic`, is there some sort of naming convention? Maybe a name-spacing like `hwverify.nic` would be better?

2018-03-27 08:32 UTC, jovial commented on specs/system_nic.rst
> +order to negate operational differences, all of the devices should run the same
I can't think of a use case for having multiple different firmware versions for the same NIC across the cluster. Is that something you are likely to do in practice?

2018-03-27 08:37 UTC, dougszumski commented
If it helps with the naming here are the upstream managers:

https://github.com/openstack/ironic-python-agent/tree/master/ironic_python_agent/hardware_managers

2018-03-28 11:42 UTC, dougszumski approved these changes

2018-03-28 13:23 UTC, oneswig commented on specs/system_nic.rst
> +order to negate operational differences, all of the devices should run the same
Suppose you've got a million nodes in production and then you buy some new hardware that comes with updated NIC firmware.  Both models are working with the firmware they have.

I guess we have to trade off between managing distinct firmware versions for different nodes versus supporting multiple permitted versions for all nodes.  Given the expected firmware value is a per-node attribute, perhaps we should focus our efforts on the former.

2018-03-28 13:28 UTC, oneswig approved these changes
Octonauts, let's do this.

2018-03-28 17:11 UTC, merged